spec_version: v1
kind: python
name: blocking_pluginv3
description: Pre-invoke plugin for input blocking
package_root: input_blocking_test_agentv3/plugins/blocking_pluginv3
tools:
  - path: blocking_pluginv3.py
